<link rel="stylesheet" href="css/entrar-registrar.css">
<main>
    <section class="entrar">
        <div class="center">
            <h3>Entrar</h3>
            <form action="#">
                <div class="box-input">
                    <label for="emailEntrar">E-mail:</label>
                    <input type="email" name="emailEntrar" id="emailEntrar" required>
                </div>
                <div class="box-input">
                    <label for="passwordEntrar">Senha:</label>
                    <div class="password">
                        <input type="password" name="passwordEntrar" id="passwordEntrar" required>
                        <i class="see entrar fa-regular fa-eye"></i>
                        <i class="not-see entrar fa-regular fa-eye-slash"></i>
                    </div>
                </div>
                <p class="msgSuccess">{{msgSuccessE}}</p>
                <p class="msgError">{{msgErrorE}}</p>
                <button type="submit">Entrar</button>
            </form>
        </div>
    </section>
    <section class="registrar">
        <div class="center">
            <h3>Criar conta</h3>
            <form action="/registrar" method="post">
                <div class="box-input">
                    <label for="name">Nome:</label>
                    <input type="text" name="name" id="name" required>
                </div>
                <div class="box-input">
                    <label for="lastName">Sobrenome:</label>
                    <input type="text" name="lastName" id="lastName" required>
                </div>
                <div class="box-input">
                    <label for="emailRegistrar">E-mail:</label>
                    <input type="email" name="emailRegistrar" id="emailRegistrar" placeholder="Ex: nome@gmail.com" required>
                </div>
                <div class="box-input">
                        <label for="passwordRegistrar">Senha:</label>
                    <div class="password">
                        <input type="password" name="passwordRegistrar" id="passwordRegistrar" minlength="4" placeholder="Digite uma senha acima de 4 caracteres" required>
                        <i class="see registrar fa-regular fa-eye"></i>
                        <i class="not-see registrar fa-regular fa-eye-slash"></i>
                    </div>
                </div>
                <div class="box-input">
                        <label for="password-Registrar-CS">Confirmar senha:</label>
                    <div class="password">
                        <input type="password" name="passwordCS" id="password-Registrar-CS" minlength="4" placeholder="Confirme sua senha" required>
                        <i class="see registrarCS fa-regular fa-eye"></i>
                        <i class="not-see registrarCS fa-regular fa-eye-slash"></i>
                    </div>
                </div>
                    <p class="msgSuccess">{{msgSuccessR}}</p>
                    <p class="msgError">{{msgErrorR}}</p>
                <button type="submit">Registrar</button>
            </form>
        </div>
    </section>
</main>
<script src="js/scripts.js"></script>